import React, { useState, useEffect } from 'react'
import { Search, Filter, ShieldAlert, AlertTriangle, RefreshCw, ChevronLeft, ChevronRight } from 'lucide-react'
import { getAlerts, getAlertStats } from '../api/alerts'
import { AlertSeverityBadge, AlertStatusBadge } from '../components/alerts/AlertBadges'
import { AlertDetail } from '../components/alerts/AlertDetail'

export function Alerts() {
  const [alerts, setAlerts] = useState([])
  const [stats, setStats] = useState(null)
  const [total, setTotal] = useState(0)
  const [totalPages, setTotalPages] = useState(0)
  const [page, setPage] = useState(1)
  const [limit] = useState(20)

  // Filters
  const [statusFilter, setStatusFilter] = useState('')
  const [severityFilter, setSeverityFilter] = useState('')
  const [search, setSearch] = useState('')

  const [selectedAlertId, setSelectedAlertId] = useState(null)
  const [loading, setLoading] = useState(true)

  const fetchAlertsData = async () => {
    try {
      setLoading(true)
      const [aData, sData] = await Promise.all([
        getAlerts({ page, limit, status: statusFilter, severity: severityFilter, search }),
        getAlertStats(),
      ])
      setAlerts(aData.data || [])
      setTotal(aData.total || 0)
      setTotalPages(aData.total_pages || 0)
      setStats(sData)
    } catch (err) {
      console.error(err)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchAlertsData()
  }, [page, statusFilter, severityFilter])

  const handleSearchSubmit = (e) => {
    e.preventDefault()
    setPage(1)
    fetchAlertsData()
  }

  return (
    <div className="space-y-6 text-left">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900/60 p-6 rounded-2xl border border-slate-800">
        <div>
          <h2 className="text-2xl font-black tracking-tight text-white flex items-center gap-2">
            <ShieldAlert className="w-6 h-6 text-rose-400" /> Security Risk Alert Management
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Real-time alert queue generated by automated ML risk engine policies.
          </p>
        </div>

        <button
          onClick={fetchAlertsData}
          className="p-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold flex items-center space-x-2 transition-all border border-slate-700 self-start md:self-auto"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          <span>Refresh Queue</span>
        </button>
      </div>

      {/* KPI Cards */}
      {stats && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-left">
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-4 space-y-1">
            <p className="text-[11px] font-medium text-slate-400">Total Alerts</p>
            <p className="text-xl font-black text-slate-100">{stats.total}</p>
          </div>
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-4 space-y-1">
            <p className="text-[11px] font-medium text-slate-400">Active Unresolved</p>
            <p className="text-xl font-black text-rose-400">{stats.open}</p>
          </div>
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-4 space-y-1">
            <p className="text-[11px] font-medium text-slate-400">Under Investigation</p>
            <p className="text-xl font-black text-amber-400">{stats.investigating}</p>
          </div>
          <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-4 space-y-1">
            <p className="text-[11px] font-medium text-slate-400">Critical Severity</p>
            <p className="text-xl font-black text-rose-500">{stats.critical}</p>
          </div>
        </div>
      )}

      {/* Search & Filter Bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 space-y-4">
        <form onSubmit={handleSearchSubmit} className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          
          <div className="relative">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search Alert ID or Transaction ID..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-3 py-2 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-cyan-500"
            />
          </div>

          <select
            value={statusFilter}
            onChange={(e) => { setStatusFilter(e.target.value); setPage(1); }}
            className="py-2 px-3 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
          >
            <option value="">All Statuses</option>
            <option value="OPEN">OPEN (Unresolved)</option>
            <option value="INVESTIGATING">INVESTIGATING</option>
            <option value="RESOLVED">RESOLVED</option>
            <option value="DISMISSED">DISMISSED</option>
          </select>

          <select
            value={severityFilter}
            onChange={(e) => { setSeverityFilter(e.target.value); setPage(1); }}
            className="py-2 px-3 rounded-xl bg-slate-950 border border-slate-800 text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
          >
            <option value="">All Severities</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>

        </form>
      </div>

      {/* Alerts Table & Mobile Cards */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 space-y-4">
        
        {/* Desktop Table View */}
        <div className="hidden sm:block overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400 font-semibold uppercase text-[10px] tracking-wider">
                <th className="py-2.5 px-3">Alert ID</th>
                <th className="py-2.5 px-3">Transaction ID</th>
                <th className="py-2.5 px-3">Score</th>
                <th className="py-2.5 px-3">Severity</th>
                <th className="py-2.5 px-3">Primary Signal</th>
                <th className="py-2.5 px-3">Status</th>
                <th className="py-2.5 px-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {loading ? (
                <tr>
                  <td colSpan="7" className="py-8 text-center text-slate-500">
                    <RefreshCw className="w-5 h-5 animate-spin mx-auto mb-2 text-cyan-400" />
                    <span>Loading alert queue...</span>
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan="7" className="py-8 text-center text-slate-500">
                    No matching alerts found in active queue.
                  </td>
                </tr>
              ) : (
                alerts.map((alt) => (
                  <tr
                    key={alt.alert_id}
                    onClick={() => setSelectedAlertId(alt.alert_id)}
                    className="hover:bg-slate-800/50 cursor-pointer transition-all"
                  >
                    <td className="py-3 px-3 font-bold text-rose-400 font-mono">{alt.alert_id}</td>
                    <td className="py-3 px-3 font-bold text-cyan-400 font-mono">{alt.transaction_id}</td>
                    <td className="py-3 px-3 font-extrabold text-slate-100">{alt.risk_score} / 100</td>
                    <td className="py-3 px-3">
                      <AlertSeverityBadge severity={alt.severity} />
                    </td>
                    <td className="py-3 px-3 text-slate-300 font-mono text-[11px]">{alt.primary_risk_factor}</td>
                    <td className="py-3 px-3">
                      <AlertStatusBadge status={alt.status} />
                    </td>
                    <td className="py-3 px-3 text-right">
                      <span className="text-xs text-cyan-400 font-semibold hover:underline">Investigate →</span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* Mobile Responsive Cards View */}
        <div className="sm:hidden space-y-3">
          {loading ? (
            <div className="py-8 text-center text-slate-500">
              <RefreshCw className="w-5 h-5 animate-spin mx-auto mb-2 text-cyan-400" />
              <span>Loading alert queue...</span>
            </div>
          ) : alerts.length === 0 ? (
            <div className="py-8 text-center text-slate-500">
              No matching alerts found in active queue.
            </div>
          ) : (
            alerts.map((alt) => (
              <div
                key={alt.alert_id}
                onClick={() => setSelectedAlertId(alt.alert_id)}
                className="bg-slate-950/80 border border-slate-800 p-4 rounded-xl space-y-2.5 cursor-pointer hover:border-cyan-500/40 transition-all"
              >
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold text-rose-400">{alt.alert_id}</span>
                  <AlertSeverityBadge severity={alt.severity} />
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-400">Transaction ID:</span>
                  <span className="font-mono font-bold text-cyan-400">{alt.transaction_id}</span>
                </div>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-slate-400">Score & Signal:</span>
                  <span className="font-mono text-slate-200">{alt.risk_score}/100 • {alt.primary_risk_factor}</span>
                </div>
                <div className="pt-2 border-t border-slate-900 flex items-center justify-between">
                  <AlertStatusBadge status={alt.status} />
                  <span className="text-xs text-cyan-400 font-bold">Investigate →</span>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Pagination Bar */}
        <div className="flex items-center justify-between pt-4 border-t border-slate-800 text-xs text-slate-400">
          <span>Page {page} of {totalPages || 1}</span>

          <div className="flex items-center space-x-2">
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page <= 1}
              className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 disabled:opacity-40 text-slate-200"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page >= totalPages}
              className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 disabled:opacity-40 text-slate-200"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Alert Detail Modal */}
      {selectedAlertId && (
        <AlertDetail
          alertId={selectedAlertId}
          onClose={() => setSelectedAlertId(null)}
          onStatusUpdated={() => fetchAlertsData()}
        />
      )}

    </div>
  )
}
